version: '3.9'
services:
  db:
    image: mariadb:latest
    container_name: mysql
    hostname: localhost
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dev_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 5432:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.8.3-management
    container_name: rabbitmq
    hostname: localhost
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: redis:6.0.1
    container_name: redisDev
    hostname: localhost
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6378:6378
      - 16378:16378
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=localhost:redis:6378
    ports:
      - "8078:8081"
volumes:
  mysql_data:
  rabbitmq_data:
  redis_data: